# Generated by Django 4.1.6 on 2023-03-08 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('inception_date', models.DateTimeField()),
                ('management_name', models.CharField(max_length=200)),
                ('management_bio', models.TextField()),
                ('investment_strategy', models.TextField()),
                ('management_start_date', models.DateTimeField()),
                ('fund_yield', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('quarter', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0.0)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualfunds.fund')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField(default=0)),
                ('alpha', models.FloatField(default=0.0)),
                ('beta', models.FloatField(default=0.0)),
                ('mean_annual_return', models.FloatField(default=0.0)),
                ('r_squared', models.FloatField(default=0.0)),
                ('std_dev', models.FloatField(default=0.0)),
                ('sharpe_ratio', models.FloatField(default=0.0)),
                ('treynor_ratio', models.FloatField(default=0.0)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualfunds.fund')),
            ],
        ),
        migrations.CreateModel(
            name='Esg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_count', models.IntegerField(default=0)),
                ('peer_group', models.CharField(max_length=200)),
                ('esg_score', models.FloatField(default=0.0)),
                ('peer_esg_min', models.FloatField(default=0.0)),
                ('peer_esg_avg', models.FloatField(default=0.0)),
                ('peer_esg_max', models.FloatField(default=0.0)),
                ('env_score', models.FloatField(default=0.0)),
                ('peer_env_min', models.FloatField(default=0.0)),
                ('peer_env_avg', models.FloatField(default=0.0)),
                ('peer_env_max', models.FloatField(default=0.0)),
                ('soc_score', models.FloatField(default=0.0)),
                ('peer_soc_min', models.FloatField(default=0.0)),
                ('peer_soc_avg', models.FloatField(default=0.0)),
                ('peer_soc_max', models.FloatField(default=0.0)),
                ('gov_score', models.FloatField(default=0.0)),
                ('peer_gov_min', models.FloatField(default=0.0)),
                ('peer_gov_avg', models.FloatField(default=0.0)),
                ('peer_gov_max', models.FloatField(default=0.0)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualfunds.fund')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField()),
                ('cash', models.FloatField(default=0.0)),
                ('stocks', models.FloatField(default=0.0)),
                ('bonds', models.FloatField(default=0.0)),
                ('others', models.FloatField(default=0.0)),
                ('preferred', models.FloatField(default=0.0)),
                ('convertible', models.FloatField(default=0.0)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualfunds.fund')),
            ],
        ),
    ]
